"""Centralized constants for the licence API."""

from licence_api.constants.validation import (
    # License constants
    ALLOWED_LICENSE_STATUSES,
    ALLOWED_LICENSE_SORT_COLUMNS,
    DEFAULT_LICENSE_SORT_COLUMN,
    # Employee constants
    ALLOWED_EMPLOYEE_STATUSES,
    ALLOWED_EMPLOYEE_SOURCES,
    ALLOWED_EMPLOYEE_SORT_COLUMNS,
    DEFAULT_EMPLOYEE_SORT_COLUMN,
    # Service/Admin account constants
    ALLOWED_SERVICE_LICENSE_SORT_COLUMNS,
    ALLOWED_ADMIN_LICENSE_SORT_COLUMNS,
    DEFAULT_SERVICE_LICENSE_SORT_COLUMN,
    # Pagination constants
    DEFAULT_PAGE_SIZE,
    MAX_PAGE_SIZE,
    MAX_BULK_OPERATION_SIZE,
    MAX_EXPORT_RECORDS,
    # Rate limit constants
    SENSITIVE_OPERATION_LIMIT,
    ADMIN_SENSITIVE_LIMIT,
    # Password constants
    MIN_PASSWORD_LENGTH,
    MAX_PASSWORD_LENGTH,
)

__all__ = [
    # License
    "ALLOWED_LICENSE_STATUSES",
    "ALLOWED_LICENSE_SORT_COLUMNS",
    "DEFAULT_LICENSE_SORT_COLUMN",
    # Employee
    "ALLOWED_EMPLOYEE_STATUSES",
    "ALLOWED_EMPLOYEE_SOURCES",
    "ALLOWED_EMPLOYEE_SORT_COLUMNS",
    "DEFAULT_EMPLOYEE_SORT_COLUMN",
    # Service/Admin accounts
    "ALLOWED_SERVICE_LICENSE_SORT_COLUMNS",
    "ALLOWED_ADMIN_LICENSE_SORT_COLUMNS",
    "DEFAULT_SERVICE_LICENSE_SORT_COLUMN",
    # Pagination
    "DEFAULT_PAGE_SIZE",
    "MAX_PAGE_SIZE",
    "MAX_BULK_OPERATION_SIZE",
    "MAX_EXPORT_RECORDS",
    # Rate limits
    "SENSITIVE_OPERATION_LIMIT",
    "ADMIN_SENSITIVE_LIMIT",
    # Password
    "MIN_PASSWORD_LENGTH",
    "MAX_PASSWORD_LENGTH",
]
